name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        symfony:
          - ^3.4
          - ~4.0
          - ~4.1
          - ~4.2
          - ~4.3
          - ^4.4
          - ~5.0
          - ~5.1
          - ~5.2
          - ~5.3
          - ^5.4

    name: 'PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install symfony/flex
        run: |
          composer require --dev symfony/flex --no-progress --no-interaction --no-install --no-interaction --no-scripts
          rm composer.lock

      - name: Lock Symfony version in composer.json
        run: composer config extra.symfony.require '${{ matrix.symfony }}' --no-interaction  --no-scripts

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: locked
          composer-options: --prefer-dist --no-scripts

      - name: PHPUnit
        run: vendor/bin/phpunit
